name: Build and Deploy Docker Image to ECR

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to AWS ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_NAME="my-app" # Replace with your image name
        TAG=$(date +'%d%m%Y-%H-%M')
        docker build -t $IMAGE_NAME:$TAG .

    # Push the Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        IMAGE_NAME="my-app" # Replace with your image name
        TAG=$(date +'%d%m%Y-%H-%M')
        REPOSITORY_URI="your_ecr_repository_uri" # Replace with your ECR repository URI
        docker tag $IMAGE_NAME:$TAG $REPOSITORY_URI:$TAG
        docker push $REPOSITORY_URI:$TAG

    # Update the ECS service with the latest image
    - name: Update ECS service
      uses: aws-actions/amazon-ecs-update-service@v1
      with:
        cluster: your-cluster-name # Replace with your ECS cluster name
        service: your-service-name # Replace with your ECS service name
        image: your_ecr_repository_uri:$TAG # The image tag to deploy

    # Optional: Clean up Docker images after use
    - name: Docker prune
      run: docker system prune -af
